### ISSUE TITLE
Component won't load

### ISSUE THREAD

**Issue by ThomasPf-git** [babaktaremi/GoogleCaptchaComponent#1]
I get this error in browser Console when loading a page where I use the GoogleCaptchaComponent:

```
recaptcha__en.js:9 Uncaught Error: reCAPTCHA placeholder element must be an element or id
    at recaptcha__en.js:9
    at JsOfReCAPTCHA.js:6
```

After refreshing the page a few times (5-10 times), it finally loads and works. What could be the problem there?

(tested it in brandnew chromium installation, so the reason cant be because of privacy and security settings in the browser, right?)

**Comment by babaktaremi** [comment]
Hi Thomas.Sorry for answering late I was pretty busy this week. What is the version that you are currently using?
