### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by devabady** [babaktaremi/GoogleCaptchaComponent#12]
After installing your component from NuGet, I noticed that when I try to add the service, there is no extension method available in the service, and the namespace name cannot be found

**Comment by babaktaremi** [comment]
Which version of NET and the package you are using? Can you provide the code snippet?
There is an extension method on `IServiceCollection` that configures the necessary services behind the scene:

```csharp

using GoogleCaptchaComponent;
using GoogleCaptchaComponent.Configuration;

builder.Services.AddGoogleCaptcha(configuration =>
        {
            configuration.V2SiteKey = v2SiteKey;
            configuration.V3SiteKey = v3SiteKey;
            configuration.DefaultVersion = CaptchaConfiguration.Version.V2;
            configuration.DefaultTheme = CaptchaConfiguration.Theme.Light;
        });
```

**Comment by devabady** [comment]
NET 6, after installing your package, I couldn't find the 'googlecaptcha' namespace. I followed your installation steps as instructed

**Comment by devabady** [comment]
Absolutely, you've made a lot of changes in version 4. Is there a way to migrate to version 4 in .NET 6

**Comment by devabady** [comment]
okay thanks , Buy you should specify the version you're installing the package for, so that the developer knows that this package is not compatible with .NET 6

**Comment by babaktaremi** [comment]
> Okay, thanks. However, you should specify the package version so that when a developer tries to install the package from NuGet, a message will appear indicating that the package is not compatible with .NET 6, and the package won't be installed

Thanks for your suggestion but Nuget already lists package dependencies
