### ISSUE TITLE
google reCAPTCHA component parameter Not found   

### ISSUE THREAD

**Issue by devabady** [babaktaremi/GoogleCaptchaComponent#13]
Hey there,

After updating my project to .NET 8, I installed Google Recaptcha and imported all the namespaces in _import.razor. However, I noticed that the Google Recaptcha component is missing the following parameters:

- SuccessCallBack
- TimeOutCallBack
- ServerValidationErrorCallBack
- ServerSideValidationHandler
- Version
- Theme

Please refer to the attached screenshot for clarification. ]
![Screenshot google recaptcha](https://github.com/babaktaremi/GoogleCaptchaComponent/assets/84203457/cb5941c9-e5c5-40d7-b9d8-090d4872970d)

**Comment by babaktaremi** [comment]
just tested it. Everything works fine. check whether you put <> ,</> in correct positions

![image](https://github.com/babaktaremi/GoogleCaptchaComponent/assets/50941767/7a7732c3-791d-41f5-9c85-591fea1a3913)

**Comment by babaktaremi** [comment]
code snippet:

```html
<GoogleRecaptcha SuccessCallBack="SuccessCallBack"
                 ServerSideValidationHandler="ServerSideValidationHandler"
                 Version="CaptchaConfiguration.Version.V2"
                 Theme="CaptchaConfiguration.Theme.Light"
                 TimeOutCallBack="Callback"
                 ServerValidationErrorCallBack="ServerSideErrorCallback"
>                
</GoogleRecaptcha>
```

**Comment by devabady** [comment]
absolutely  it's in the right place, but tbh idk what is the problem

**Comment by babaktaremi** [comment]
> is there any documentation for Google Recaptcha 2.0? i need to try it

 Google docs : https://developers.google.com/recaptcha/intro

**Comment by devabady** [comment]
no i mean your component

**Comment by babaktaremi** [comment]
> no i mean your component

Refer to Readme . Also you can get the code from the repo!
