### ISSUE TITLE
reCAPTCHA couldn't find user-provided function: onloadCallback

### ISSUE THREAD

**Issue by innovadev2024** [babaktaremi/GoogleCaptchaComponent#19]
Hello, I have a problem with the component the captcha not show and got this error,  I using net core 8 blazor server mode

reCAPTCHA couldn't find user-provided function: onloadCallback

Thanks for any help

**Comment by babaktaremi** [comment]
Hi. Beed more info. Which version are yoylu using? can provide the project or code snippet?

**Comment by innovadev2024** [comment]
> Hi. Beed more info. Which version are yoylu using? can provide the project or code snippet?

Hi I can't provide the project unfortunately, but if this helps  I use net core 8 with blazor server mode,  I try to use captcha V3

**Comment by babaktaremi** [comment]
> > Hi. Beed more info. Which version are yoylu using? can provide the project or code snippet?
> 
> 
> 
> Hi I can't provide the project unfortunately, but if this helps  I use net core 8 with blazor server mode,  I try to use captcha V3

What rendering mode is configured for the page using the captcha?

**Comment by innovadev2024** [comment]
> > > Hi. Beed more info. Which version are yoylu using? can provide the project or code snippet?
> > 
> > 
> > Hi I can't provide the project unfortunately, but if this helps  I use net core 8 with blazor server mode,  I try to use captcha V3
> 
> What rendering mode is configured for the page using the captcha?

**@rendermode InteractiveServer**

![image](https://github.com/babaktaremi/GoogleCaptchaComponent/assets/167388824/3c789731-35a9-4278-b701-56a5293ff03b)

**Comment by babaktaremi** [comment]
Set the detailed errors to true. This information does not help

**Comment by innovadev2024** [comment]
> Set the detailed errors to true. This information does not help

**here the details**

![image](https://github.com/babaktaremi/GoogleCaptchaComponent/assets/167388824/3314cec5-f545-4506-8a2f-0713300082a6)

**Comment by babaktaremi** [comment]
> > Set the detailed errors to true. This information does not help
> 
> 
> 
> **here the details**
> 
> 
> 
> ![image](https://github.com/babaktaremi/GoogleCaptchaComponent/assets/167388824/3314cec5-f545-4506-8a2f-0713300082a6)
> 
> 

have you referenced the loader script in .html file?

```html
<script src="_content/GoogleCaptchaComponent/Scripts/ScriptLoader.js"></script>
````

**Comment by innovadev2024** [comment]
> > > Set the detailed errors to true. This information does not help
> > 
> > 
> > **here the details**
> > ![image](https://private-user-images.githubusercontent.com/167388824/328944038-3314cec5-f545-4506-8a2f-0713300082a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxODE5ODcsIm5iZiI6MTcxNTE4MTY4NywicGF0aCI6Ii8xNjczODg4MjQvMzI4OTQ0MDM4LTMzMTRjZWM1LWY1NDUtNDUwNi04YTJmLTA3MTMzMDAwODJhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOFQxNTIxMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWYxOGUxZmY1NjQ4ZjE5ZjUwODMyM2M5NzFiZmU4YWY3ZDQxMWI2N2JlNzhjZTNkYTBjOWUxNGNmNjg0ZTYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cwgeQVXp8jqCZvbQSLAj7QVMHEYuE9rYI4nkbZyWkkg)
> 
> have you referenced the loader script in .html file?
> 
> ```
> <script src="_content/GoogleCaptchaComponent/Scripts/ScriptLoader.js"></script>
> ```

**in the case of the server mode for blazor, doesn't have a html page, I try to add then href in the MainLayout.blazor but I think doesn't work**  

![image](https://github.com/babaktaremi/GoogleCaptchaComponent/assets/167388824/2762da8b-c412-45a5-a896-6405cc3acef6)

**Comment by innovadev2024** [comment]
I found the problem I need to put the script in the App.razor and now it works thank you.

![image](https://github.com/babaktaremi/GoogleCaptchaComponent/assets/167388824/eec69a3d-c488-4f59-9623-75aa2d9074a3)
