### ISSUE TITLE
Undefined GoogleCaptchaCheckResponseResult model in ServerSideValidationHandler example in README.md

### ISSUE THREAD

**Issue by omgitsjan** [babaktaremi/GoogleCaptchaComponent#3]
Hello [babaktaremi](https://github.com/babaktaremi),

I was reading the README.md of this project and noticed that the ServerSideValidationHandler example uses a model named GoogleCaptchaCheckResponseResult that doesn't seem to be defined or imported in the provided example code, maybe i am also missing something​.

```
private async Task<ServerSideCaptchaValidationResultModel> ServerSideValidationHandler(ServerSideCaptchaValidationRequestModel requestModel)
{
    using var httpClient = new HttpClient();
    var apiResult = await httpClient.GetFromJsonAsync<**GoogleCaptchaCheckResponseResult**>($"https://api.mysecurewebsite.com/VerifyCaptcha?token={requestModel.CaptchaResponse}");
    return new ServerSideCaptchaValidationResultModel(apiResult.Success, string.Join("\n",apiResult.ErrorCodes ?? new List<string>(){"No Error"}));
}
```
This might lead to confusion for users trying to implement the example as it is.

Could you please clarify this in the README, either by defining what GoogleCaptchaCheckResponseResult is supposed to be, or by replacing it with a predefined model?

Thank you!

**Comment by omgitsjan** [comment]
I have now seen the model in the sample files that I missed, maybe a little hint in the readme would be quite good, because at first glance it looked like an imported model 😄 

```
 namespace GoogleCaptcha.Exmaple
{
    public class GoogleCaptchaCheckResponseResult
    {
        [JsonPropertyName("success")]
        public bool Success { get; set; }

        [JsonPropertyName("error-codes")]
        public List<string> ErrorCodes { get; set; }
    }
}
```

**Comment by babaktaremi** [comment]
That is a model example . You can set any model related to captcha validation (because the validation should be done on behalf your own api)

**Comment by babaktaremi** [comment]
> Yeah, I should have checked the example first, it all makes much more sense now. Sorry for the disturbance 😅
No worries at all! Happy Coding😃
