### ISSUE TITLE
Logging in ScriptLoader.js

### ISSUE THREAD

**Issue by Dalto1** [babaktaremi/GoogleCaptchaComponent#4]
Can we remove all the console logging in ScriptLoader.js? 

line 5 : `console.log(scriptPath + " already loaded");`
line 28 :  `console.log(scriptPath + " created");`
line 35 : `console.log(scriptPath + " loaded ok");`
line 41 : `console.log(scriptPath + " load failed");`

**Comment by babaktaremi** [comment]
Hi . Sorry for the late response (Had a pretty busy month). 
I'll work on an update to address these issues

**Comment by babaktaremi** [comment]
version 3.1.0 is currently in validating process and will be listed in the next couple of hours. I just removed the logging code. Currently waiting for NET 8 stable release . with NET8 I'll add logging level options as a feature and there will be some performance improvements!
