### ISSUE TITLE
Is there a way to make the component not visible till the button is clicked

### ISSUE THREAD

**Issue by vnetonline** [babaktaremi/GoogleCaptchaComponent#6]

**Comment by vnetonline** [comment]
How would I then submit the form using the same button

**Comment by babaktaremi** [comment]
After user successfully passed the captcha challenge, you will receive a captcha response that you can send to your server along side your form data and check the validity of captcha response with private key (that you received along with captcha key in recaptcha admin console) from there

**Comment by vnetonline** [comment]
I am using the Oqtane framework and don't want to put the registration in the Program.cs can I use the IStratupCollection class to configure the services ??

**Comment by vnetonline** [comment]
This is how I have registered Radars

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Oqtane.Infrastructure;
using Radzen;

namespace Amazing.Module.Audiences.Server.Startup
{
    public class ServerStartup : IServerStartup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddScoped<DialogService>();
            services.AddScoped<NotificationService>();
            services.AddScoped<TooltipService>();
            services.AddScoped<ContextMenuService>();
        }
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env) { }
        public void ConfigureMvc(IMvcBuilder mvcBuilder) { }
    }

}

**Comment by babaktaremi** [comment]
Yes you can 
just don't forget to call IStratupCollection in the Program.cs 😉

**Comment by babaktaremi** [comment]
Wait a minute, are you using Blazor or asp net core MVC?

**Comment by vnetonline** [comment]
Oqtane is a Blazor framework you can check it out at https://oqtane.org

**Comment by vnetonline** [comment]
Seems that render_captcha_v3 doesn't always fire do you know why this would be ??

**Comment by babaktaremi** [comment]
> Seems that render_captcha_v3 doesn't always fire do you know why this would be ??

I need more details about this
Does browser console logs any error?
In which situations does it usually happen?

**Comment by vnetonline** [comment]
It's okay I figured it out because I am using it Oqtane it's has own way of loading JavaScript using introp and it was the ordering of how I was calling it it's working very well

**Comment by babaktaremi** [comment]
> It's okay I figured it out because I am using it in Oqtane it's has own way of loading JavaScript using introp and it was the ordering of how I was calling it is working very well

Fantastic! . Closing the issue . Feel free to reopen it if any other issues happened in the future. Happy coding!
