### ISSUE TITLE
recaptcha V2 reset

### ISSUE THREAD

**Issue by GeorgeStephens** [babaktaremi/GoogleCaptchaComponent#8]
Hi, 

I've been using this control in Wasm and it works really well, but is there a way to reset it?

We use it to verify people are, well, human, before we verify their password. So if they get their password wrong, you then have to wait for the timeout before you can try again as you cant use the same token twice.

**Comment by babaktaremi** [comment]
That's a really nice feature to have. I will add it for the next update

**Comment by babaktaremi** [comment]
> Hi,
> 
> I've been using this control in Wasm and it works really well, but is there a way to reset it?
> 
> We use it to verify people are, well, human, before we verify their password. So if they get their password wrong, you then have to wait for the timeout before you can try again as you cant use the same token twice.


Reload Method Added to Version 3.5 . Please update and let me know if there are any issues!

Docs:
https://github.com/babaktaremi/GoogleCaptchaComponent#refreshing-the-captcha-manually

**Comment by GeorgeStephens** [comment]
Like a dream! I've created a pull request for updating the docs to include adding Models and Services
