### ISSUE TITLE
reCaptcha v3

### ISSUE THREAD

**Issue by bkristesiashvili** [babaktaremi/GoogleCaptchaComponent#9]
at the first load of the page, reCaptcha works correctly but when we try to reload/refresh the page it does not work.

**Comment by babaktaremi** [comment]
Please provide more details.

**Comment by bkristesiashvili** [comment]
we have 	`<script src="js/ScriptLoader.js"></script>` into _Layout.cshtml and 
```
<GoogleRecaptcha SuccessCallBack="SuccessCallBack"
                                     TimeOutCallBack="TimeOutCallBack"
                                     ServerValidationErrorCallBack="ServerSideValidationError"
                                     ServerSideValidationHandler="ServerSideValidationHandler">
</GoogleRecaptcha>
```

on the razor page, at the first load it works,  we get a reCaptcha token, but when we hit the refresh page it has a problem

**Comment by babaktaremi** [comment]
I cannot reproduce the error. Need more details ( The version that you are using , the NET version and whether it's Blazor Server or web assembly)

**Comment by bkristesiashvili** [comment]
Blazor Server - .NET 7

**Comment by babaktaremi** [comment]
I some how can't reproduce the problem. I refreshed to page thousand of times and each time it works as it should be. Is your captcha site token correct? can browser connect to google recaptcha service?

**Comment by bkristesiashvili** [comment]
can you give us the example that you already tested?

**Comment by Dchipp7** [comment]
I have tried your newest addition ReloadAsync Method but it still does not render the component once again , i am working on a same project as bkristesiashvili

**Comment by babaktaremi** [comment]
> I have tried your newest addition ReloadAsync Method but it still does not render the component once again , i am working on a same project as bkristesiashvili

Reload Method only works on V2 version. Are your domains defined in Recaptcha Admin Panel Correct?

**Comment by babaktaremi** [comment]
> can you give us the example that you already tested?

Blazor Server test project added to the repo.
I think I solved the bug. It was the cache container for script loader (which was registered as singleton. changed it to scoped to be registered once per connection instead of per application. And since scoped and singleton are same in WASM , hopefully it won't produce any bugs in WASM projects). 
Please update to version 3.6.0 and check if this solves the issue
